steps:
- name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  id: build
  args: ["clean", "package", "appengine:deploy"]
  
#  
#- name: "gcr.io/cloud-builders/gcloud"
#  args: ["app", "deploy"]
#timeout: "1600s"